services:
  - type: web
    name: xarajat-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: uvicorn core.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
