# Generated by Django 6.0.6 on 2026-06-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
