# Generated by Django 6.0.6 on 2026-06-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramgroup_expense_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
